FEW_SHOT_EXAMPLES = [{
    "state": {
        "env_state": {
            "biome_id": 0,
            "biome_rainfall": 0.5,
            "biome_temperature": 0.6,
            "can_see_sky": "true",
            "is_raining": "false",
            "light_level": 15,
            "sea_level": 63,
            "sky_light_level": 0.71,
            "sun_brightness": 0.94
        },
        "player_pos": {
            "x": -5916.523596717107,
            "y": 72.162141421027,
            "z": -4678.105283613979,
            "pitch": -25.790506,
            "yaw": -15.180989
        },
        "blocks": [
            {"x": -2, "y": -2, "z": -2, "type": "minecraft:dirt"},
            {"x": -2, "y": -2, "z": -1, "type": "minecraft:dirt"},
            {"x": -2, "y": -2, "z": 0, "type": "minecraft:dirt"},
            {"x": -2, "y": -2, "z": 1, "type": "minecraft:stone"},
            {"x": -2, "y": -1, "z": -2, "type": "minecraft:grass_block"},
            {"x": -2, "y": -1, "z": -1, "type": "minecraft:grass_block"},
            {"x": -2, "y": -1, "z": 0, "type": "minecraft:dirt"},
            {"x": -2, "y": -1, "z": 1, "type": "minecraft:stone"},
            {"x": -2, "y": 0, "z": -2, "type": "minecraft:grass"},
            {"x": -2, "y": 0, "z": 0, "type": "minecraft:grass_block"},
            {"x": -2, "y": 0, "z": 1, "type": "minecraft:dirt"},
            {"x": -2, "y": 1, "z": 1, "type": "minecraft:dirt"},
            {"x": -1, "y": -2, "z": -2, "type": "minecraft:dirt"},
            {"x": -1, "y": -2, "z": -1, "type": "minecraft:dirt"},
            {"x": -1, "y": -2, "z": 0, "type": "minecraft:dirt"},
            {"x": -1, "y": -2, "z": 1, "type": "minecraft:dirt"},
            {"x": -1, "y": -1, "z": -2, "type": "minecraft:grass_block"},
            {"x": -1, "y": -1, "z": -1, "type": "minecraft:grass_block"},
            {"x": -1, "y": -1, "z": 0, "type": "minecraft:grass_block"},
            {"x": -1, "y": -1, "z": 1, "type": "minecraft:dirt"},
            {"x": -1, "y": 0, "z": -1, "type": "minecraft:grass"},
            {"x": -1, "y": 0, "z": 1, "type": "minecraft:grass_block"},
            {"x": 0, "y": -2, "z": -2, "type": "minecraft:grass_block"},
            {"x": 0, "y": -2, "z": -1, "type": "minecraft:grass_block"},
            {"x": 0, "y": -2, "z": 0, "type": "minecraft:dirt"},
            {"x": 0, "y": -2, "z": 1, "type": "minecraft:dirt"},
            {"x": 0, "y": -1, "z": -2, "type": "minecraft:grass"},
            {"x": 0, "y": -1, "z": -1, "type": "minecraft:grass"},
            {"x": 0, "y": -1, "z": 0, "type": "minecraft:grass_block"},
            {"x": 0, "y": -1, "z": 1, "type": "minecraft:grass_block"},
            {"x": 1, "y": -2, "z": -2, "type": "minecraft:grass_block"},
            {"x": 1, "y": -2, "z": -1, "type": "minecraft:grass_block"},
            {"x": 1, "y": -2, "z": 0, "type": "minecraft:grass_block"},
            {"x": 1, "y": -2, "z": 1, "type": "minecraft:grass_block"},
            {"x": 1, "y": -1, "z": -2, "type": "minecraft:grass"},
            {"x": 1, "y": -1, "z": -1, "type": "minecraft:grass"}
        ],
        "mobs": [
            {"x": -1.3004882492459728, "y": -0.1621414210270018, "z": -2.4067932615125756, "name": "CowEntity"},
            {"x": 1.6101072775045395, "y": -1.1621414210270018, "z": -3.107322485219811, "name": "CowEntity"}
        ],
        "health": 20.0,
        "hunger": 20,
        "is_gui_open": "false",
        "inventory": {
            "0": {"type": "iron_sword", "quantity": 1},
            "1": {"type": "diamond", "quantity": 64},
            "2": {"type": "bread", "quantity": 16},
            "3": {"type": "apple", "quantity": 16},
            "4": {"type": "iron_sword", "quantity": 1},
            "5": {"type": "none", "quantity": 0},
            "6": {"type": "none", "quantity": 0},
            "7": {"type": "none", "quantity": 0},
            "8": {"type": "none", "quantity": 0},
            "9": {"type": "none", "quantity": 0},
            "10": {"type": "none", "quantity": 0},
            "11": {"type": "none", "quantity": 0},
            "12": {"type": "none", "quantity": 0},
            "13": {"type": "none", "quantity": 0},
            "14": {"type": "none", "quantity": 0},
            "15": {"type": "none", "quantity": 0},
            "16": {"type": "none", "quantity": 0},
            "17": {"type": "none", "quantity": 0},
            "18": {"type": "none", "quantity": 0},
            "19": {"type": "none", "quantity": 0},
            "20": {"type": "none", "quantity": 0},
            "21": {"type": "none", "quantity": 0},
            "22": {"type": "none", "quantity": 0},
            "23": {"type": "none", "quantity": 0},
            "24": {"type": "none", "quantity": 0},
            "25": {"type": "none", "quantity": 0},
            "26": {"type": "none", "quantity": 0},
            "27": {"type": "none", "quantity": 0},
            "28": {"type": "none", "quantity": 0},
            "29": {"type": "none", "quantity": 0},
            "30": {"type": "none", "quantity": 0},
            "31": {"type": "none", "quantity": 0},
            "32": {"type": "none", "quantity": 0},
            "33": {"type": "none", "quantity": 0},
            "34": {"type": "none", "quantity": 0},
            "35": {"type": "none", "quantity": 0}
        },
        "inventory_agg": {
            "iron_sword": 2,
            "diamond": 64,
            "bread": 16,
            "apple": 16
        },
        "equipped_items": {
            "chest": {"damage": 0, "maxDamage": 0, "type": "air"},
            "feet": {"damage": 0, "maxDamage": 0, "type": "air"},
            "head": {"damage": 0, "maxDamage": 0, "type": "air"},
            "legs": {"damage": 0, "maxDamage": 0, "type": "air"},
            "mainhand": {"damage": 0, "maxDamage": 0, "type": "air"},
            "offhand": {"damage": 0, "maxDamage": 0, "type": "air"}
        },
        "extras": {
            "use_item": {},
            "pickup": {},
            "break_item": {},
            "craft_item": {},
            "mine_block": {},
            "damage_dealt": {},
            "custom": {
                "jump": 4,
                "time_since_rest": 207,
                "crouch_one_cm": 9,
                "play_one_minute": 207,
                "sprint_one_cm": 6,
                "time_since_death": 207,
                "walk_one_cm": 22,
                "sneak_time": 13
            },
            "kill_entity": {}
        }
    },
    "plan": {
        "reasoning": "Daytime on grass/dirt with stone exposed nearby; cows are passive. Full health/hunger, many diamonds but no wood/tools/armor equipped. First secure wood to unlock crafting, then convert diamonds into tools/armor and establish light/shelter.",
        "subgoals": [
            {"name": "collect wood", "params": {"count": 8}, "priority": 12},
            {"name": "craft planks", "params": {"count": 32}, "priority": 11},
        ],
        "immediate_action": "collect_wood",
        "context_notes": [
            "High light (15) and sun_brightness 0.94 — safe window",
            "Nearby stone means quick furnace setup",
            "Cows present — plan for pen/breeding later",
            "No armor equipped yet — avoid fights until geared"
        ]
    }
}]